### ISSUE TITLE
TypeORM: short term fixes und patches

### ISSUE THREAD

**Issue by davidsparkles** [fullstack-build/fullstack-one#55]
- [x] Option enum should create a type in postgres
> query: CREATE TYPE "User_size_enum" AS ENUM('small', 'medium', 'large')

- [x] Was passiert wenn das enum im pg als type angelegt wird und ein neuer value hinzugefügt wird im ts?
> Geht im Prinzip schon (siehe log). Aber wenn XXX_CREATE_ME und XXX_READ_AUTH (/_PUBLIC) existiert, passiert QueryFailedError: cannot alter type of a column used by a view or rule.
> query: START TRANSACTION
> query: ALTER TYPE "public"."User_size_enum" RENAME TO "User_size_enum_old"
> query: CREATE TYPE "User_size_enum" AS ENUM('small', 'medium', 'large', 'superLarge')
> query: ALTER TABLE "User" ALTER COLUMN "size" TYPE "User_size_enum" USING "size"::"text"::"User_size_enum"
> query: DROP TYPE "User_size_enum_old"
> query: COMMIT

- [x] Entities with EntityOptions and Directives
- [x] Support schema -> entity.schema to @table(schemaName: "public")
>   @Entity({ schema: "other" })
>   export default class Photo extends typeorm.BaseEntity
> creates
>   type Photo @table(schemaName: "other") 

- [x] `db` Paket
  - [x] Brauchen wir noch den DbGeneralPool? -> Kann weg, wenn wir an den pool von typeorm kommen
  - [x] Brauchen wir noch den DbAppClient? -> Kann weg. Hier sollte man noch testen wie sich transactions auf einer connection verhalten und ob man überhaupt mehrere connections benötigt.
  - [x] Adjust typeorm pool size gracefully
- [x] Fehler: Bei Create `GraphQLError: No uuid has been generated in this transaction.`
- [x] Fehlermeldungen ergänzen: bspw. wenn enumName da ist aber enum fehlt.
- [x] Migrations sollten auch nach dem npm run build ausführbar sein, jedes one paket registriert seine migrations
- [x] Migrations von fullstack paketen sollte beim booten programatisch gestartet werden.
- [x] inverSide argument for both OneToMany and ManyToOne. Are self-referencing relations possible?
- [x] Unique over multiple Columns -> @Unique from typeorm
- [x] Indices
- [x] Completly hide typeorm behind `db`
- [x] rename migration table to "_migrations"
- [x] Fix: QueryFailedError: relation "Photo" already exists (Die Synchronisation failed)
- [x] `events` do not work (at least on Davids Ubuntu if he uses his Docker Postgres)

- [x] Auth Decorators (privacyAgreementAcceptedVersion, ...)
- [x] Schema Builder decorators (computed, ...)
- [x] Documentation: orm-example/README.md db/ORM/README.md

**Comment by terehov** [comment]
@davidsparkles ich glaube oben fehlt noch der Partial Unique Index

**Comment by davidsparkles** [comment]
> @davidsparkles ich glaube oben fehlt noch der Partial Unique Index

Typeorm supports this:
https://typeorm.io/#indices/unique-indices
https://typeorm.io/#indices/indices-with-multiple-columns

```ts
import {Entity, PrimaryGeneratedColumn, Column, Index} from "typeorm";

@Entity()
@Index(["firstName", "lastName"])
@Index(["firstName", "middleName", "lastName"], { unique: true })
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    middleName: string;

    @Column()
    lastName: string;

}
```

Or did I got it wrong @terehov ?

**Comment by terehov** [comment]
The condition is missing:
https://www.postgresql.org/docs/8.0/indexes-partial.html

**Comment by terehov** [comment]
Scheinbar geht es, finde es aber in der Doku nicht:
https://github.com/typeorm/typeorm/issues/4171

**Comment by terehov** [comment]
@davidsparkles sagt: 
>Scheint zu funktionieren bzw. zumindest gibt es dafür typedefinitions. Vielleicht könntest du das ja beim nächsten mal wenn du den einbauen willst austesten und mal schauen ob auch alles in der Datenbank ankommt.

```
@Entity()
export class Test {
    @PrimaryGeneratedColumn()
    public id?: number;

    @Column()
    @Index({ where: '"approvedBy" IS NULL' })
    public theKey?: string;

    @Column()
    public approvedBy?: string;
}
```

**Comment by terehov** [comment]
Yes, it works!

Example:
```
@Index(["updateTime1", "updateTime2"], { unique: true, where: '"updateTime1" IS NULL OR "updateTime2" IS NULL' })
export default class Task extends BaseEntity {
  @PrimaryGeneratedColumn()
  @QueryPermissions("Anyone")
  public id: string;

  @Column({ gqlType: "String", type: "character varying" })
  @QueryPermissions(["Anyone", { name: "Owner", params: { field: "userId" } }])
  public title: string;

  @ManyToOne((type) => User, "tasks", { nullable: true })
  @QueryPermissions(["Anyone"])
  public user?: User;

  @Column({ gqlType: "String", type: "character varying" })
  @QueryPermissions(["Anyone", { name: "Owner", params: { field: "userId" } }])
  public updateTime1: string;

  @Column({ gqlType: "String", type: "character varying" })
  @QueryPermissions(["Anyone", { name: "Owner", params: { field: "userId" } }])
  public updateTime2: string;
}
```

<img width="841" alt="Screenshot 2019-07-20 at 12 21 54" src="https://user-images.githubusercontent.com/490885/61576927-15b81c00-aae9-11e9-9e0c-1cb0a097a1f7.png">

**Comment by davidsparkles** [comment]
All minor tasks completed.
