### ISSUE TITLE
Computed Column decorator using typeorm subscriptions

### ISSUE THREAD

**Issue by davidsparkles** [fullstack-build/fullstack-one#72]
https://typeorm.io/#/listeners-and-subscribers/afterload

**Comment by davidsparkles** [comment]
To don't kill the performance, cumputed columns can be added via https://typeorm.io/#/listeners-and-subscribers but maybe rather as an promise or a function returning a promise, e.g. if the user's email is a computed column.

**Comment by davidsparkles** [comment]
@dustin-H @terehov what do you think of my suggestion for computed columns:

expressions
```ts
export = [
  {
    name: "Anyone",
    type: "expression",
    gqlReturnType: "Boolean",
    generate: (context, params): string => {
      return `TRUE`;
    }
  },
  {
    name: "GetNumber",
    type: "expression",
    gqlReturnType: "Int",
    generate: (context, params) => {
      return `10`;
    }
  }
]
```

model
```ts
@Entity({ schema: "public" })
export default class Task extends BaseEntity {
  @PrimaryGeneratedColumn({ comment: "This is a very important id column." })
  @QueryPermissions("Anyone")
  public id: number;
  
  @Column({ gqlType: "String", type: "character varying" })
  @QueryPermissions("Anyone")
  public title: string;
  
  @Computed({ expression: "GetNumber", gqlType: "Int" })
  @QueryPermissions("Anyone")
  public time: () => Promise<number>;
}
```

index.ts
```ts
const task = new Task();
task.title = "Catch the train";
await task.save();
console.log("Task has been saved");

const tasks = await Task.find();
tasks.forEach(async (task) => {
  const time = await task.time();
  console.log(JSON.stringify({ ...task, time }));
});
```
Log
```sh
{"id":"8a58d888-ca3b-4c2d-8a71-af0386863d77","title":"Catch the train","time":10}
```


The graphql endpoint does not change
```graphql
{
  tasks {
    id
    title
    time
  }
}
```
Response
```json
{
  "data": {
    "tasks": [
      {
        "id": "8a58d888-ca3b-4c2d-8a71-af0386863d77",
        "title": "Catch the train",
        "time": 10
      }
    ]
  }
}
```

**Comment by davidsparkles** [comment]
@dustin-H I am currently not sure about the best way to execute an expression. Eventually, I would like to have a function, that maps the name of the schema, of the table and of the column & the name and parameters of the expression to an SQL select statement. e.g. in the case of the example above:
```ts
getExpressionsSql("public", "Task", "time", "getNumber", null);
// `SELECT 10;`
```

How do you think can we achieve this? Somewhere in `schema-builder/gql-schema-builder/createExpression.ts`?

**Comment by dustin-H** [comment]
Yes you need the class `CreateExpressions`.

First get the expressions defined in the project from `schema-builder` package:

```
const expressions = schemaBuilder.loadExpressions();
```

Then create an instance of `CreateExresssions` like this:

```
const createExpressions = new CreateExpressions(expressions, "_local_table_", true);
```

Now you can compile the expression:

```
const myExpressionObject: IExpressionInput = {  /* ... */ };
const compiledExpression = createExpressions.parseExpressionInput(myExpressionObject);
```

In the End create the SQL-Query:

```
const sql = `SELECT (${compiledExpression.sql}) "myExpressionAlias" FROM "${tableSchema}"."${tableName}" AS "_local_table_";`:
```

> Note: This query will fail if the expression requires authentication. You can check that before with `compiledExpression.requiresAuth === true`.

To get only one single row just add a `WHERE "_local_table_".id = '123'`
