### ISSUE TITLE
Graphql Test for QueryBuild does not work

### ISSUE THREAD

**Issue by davidsparkles** [fullstack-build/fullstack-one#82]
Somewhere LoggerFactory is Injected, which injects Config, which does not find a `config/default.js` in `.../node_modules/ava/...`.

**Comment by dustin-H** [comment]
Is this the reason why #81 is not building?

**Comment by terehov** [comment]
yes

**Comment by davidsparkles** [comment]
🤮

**Comment by dustin-H** [comment]
I added the logger at a few points. Do you think it helps to talk about that?
